module.exports=function(app,ctx){
const {db,save,id,user,auth,notify,broadcast,isBlocked}=ctx;
const arr=(k)=>{if(!Array.isArray(db[k]))db[k]=[];return db[k]};
for(const k of ['lives','reposts','duets','stitches','collections','playlists','subscriptions','broadcasts','drafts','groupChats','groupMembers','messageReactions','mutes','topicPrefs','keywordFilters','notInterested','appeals','storyViews','videoReports','hashtags','sounds','contentFilters'])arr(k);

function own(req,resource){return resource&&resource.userId===req.user.id}
function video(idv){return db.videos.find(v=>v.id===idv)}
function clean(s,n=500){return String(s||'').trim().slice(0,n)}

app.get('/api/features',auth,(req,res)=>res.json({version:'13.0.0',features:{live:true,duet:true,stitch:true,stories:true,reposts:true,saves:true,collections:true,playlists:true,editor:true,photoPosts:true,textPosts:true,search:true,hashtags:true,sounds:true,feedControls:true,groupChats:true,voiceMessages:true,mediaMessages:true,reactions:true,forwarding:true,studio:true,subscriptions:true,broadcasts:true,reporting:true,blocking:true,muting:true,commentFilters:true,spamProtection:true,copyrightReports:true,ageControls:true,appeals:true,coins:true,gifts:true,creatorWithdrawals:true}}));

app.post('/api/videos/:id/repost',auth,(req,res)=>{const v=video(req.params.id);if(!v)return res.status(404).json({error:'Video not found'});if(isBlocked(req.user.id,v.userId))return res.status(403).json({error:'Unavailable'});let i=arr('reposts').findIndex(x=>x.userId===req.user.id&&x.videoId===v.id);if(i>=0)arr('reposts').splice(i,1);else arr('reposts').push({id:id('rp'),userId:req.user.id,videoId:v.id,createdAt:new Date().toISOString()});save();res.json({reposted:i<0})});
app.get('/api/reposts',auth,(req,res)=>res.json(arr('reposts').filter(x=>x.userId===req.user.id).map(x=>video(x.videoId)).filter(Boolean)));

app.post('/api/videos/:id/duet',auth,(req,res)=>{const v=video(req.params.id);if(!v)return res.status(404).json({error:'Video not found'});const {url,title,description}=req.body||{};if(!url)return res.status(400).json({error:'Duet media URL is required'});const nv={id:id('v'),userId:req.user.id,creator:req.user.name,title:clean(title||'Duet with '+v.creator,120),description:clean(description||'',500),url:String(url),sourceVideoId:v.id,creationType:'duet',createdAt:new Date().toISOString(),views:0,likes:[],likedBy:[],savedBy:[],comments:[]};db.videos.push(nv);save();notify(v.userId,'duet',req.user.name+' created a duet with your video');res.json(nv)});
app.post('/api/videos/:id/stitch',auth,(req,res)=>{const v=video(req.params.id);if(!v)return res.status(404).json({error:'Video not found'});const {url,title,description}=req.body||{};if(!url)return res.status(400).json({error:'Stitch media URL is required'});const nv={id:id('v'),userId:req.user.id,creator:req.user.name,title:clean(title||'Stitch with '+v.creator,120),description:clean(description||'',500),url:String(url),sourceVideoId:v.id,creationType:'stitch',createdAt:new Date().toISOString(),views:0,likes:[],likedBy:[],savedBy:[],comments:[]};db.videos.push(nv);save();notify(v.userId,'stitch',req.user.name+' stitched your video');res.json(nv)});

app.post('/api/collections',auth,(req,res)=>{const c={id:id('col'),userId:req.user.id,name:clean(req.body?.name||'My Collection',80),videoIds:[],createdAt:new Date().toISOString()};arr('collections').push(c);save();res.json(c)});
app.get('/api/collections',auth,(req,res)=>res.json(arr('collections').filter(x=>x.userId===req.user.id)));
app.post('/api/collections/:id/videos',auth,(req,res)=>{const c=arr('collections').find(x=>x.id===req.params.id&&x.userId===req.user.id);if(!c)return res.status(404).json({error:'Collection not found'});const vid=String(req.body?.videoId||'');if(!video(vid))return res.status(404).json({error:'Video not found'});if(!c.videoIds.includes(vid))c.videoIds.push(vid);save();res.json(c)});

app.post('/api/playlists',auth,(req,res)=>{const p={id:id('pl'),userId:req.user.id,name:clean(req.body?.name||'My Playlist',80),description:clean(req.body?.description,200),videoIds:[],createdAt:new Date().toISOString()};arr('playlists').push(p);save();res.json(p)});
app.get('/api/playlists/:userId',auth,(req,res)=>res.json(arr('playlists').filter(x=>x.userId===req.params.userId)));
app.post('/api/playlists/:id/videos',auth,(req,res)=>{const p=arr('playlists').find(x=>x.id===req.params.id&&x.userId===req.user.id);if(!p)return res.status(404).json({error:'Playlist not found'});const vid=String(req.body?.videoId||'');if(!video(vid))return res.status(404).json({error:'Video not found'});if(!p.videoIds.includes(vid))p.videoIds.push(vid);save();res.json(p)});

app.post('/api/lives',auth,(req,res)=>{if(arr('lives').some(x=>x.userId===req.user.id&&x.status==='live'))return res.status(409).json({error:'You already have a LIVE session'});const l={id:id('live'),userId:req.user.id,title:clean(req.body?.title||'Zelqora LIVE',100),status:'live',viewerIds:[],guestIds:[],comments:[],giftsCoins:0,startedAt:new Date().toISOString(),replayUrl:''};arr('lives').push(l);broadcast({type:'live_started',live:l});save();res.json(l)});
app.get('/api/lives',auth,(req,res)=>res.json(arr('lives').filter(x=>x.status==='live').slice(-50).reverse().map(x=>({...x,viewerCount:x.viewerIds.length,guestCount:x.guestIds.length}))));
app.get('/api/lives/:id',auth,(req,res)=>{const l=arr('lives').find(x=>x.id===req.params.id);if(!l)return res.status(404).json({error:'LIVE not found'});res.json({...l,viewerCount:l.viewerIds.length,guestCount:l.guestIds.length})});
app.post('/api/lives/:id/join',auth,(req,res)=>{const l=arr('lives').find(x=>x.id===req.params.id&&x.status==='live');if(!l)return res.status(404).json({error:'LIVE not found'});if(!l.viewerIds.includes(req.user.id))l.viewerIds.push(req.user.id);save();broadcast({type:'live_viewer',liveId:l.id,count:l.viewerIds.length});res.json({ok:true,viewerCount:l.viewerIds.length})});
app.post('/api/lives/:id/comment',auth,(req,res)=>{const l=arr('lives').find(x=>x.id===req.params.id&&x.status==='live');if(!l)return res.status(404).json({error:'LIVE not found'});const c={id:id('lc'),userId:req.user.id,name:req.user.name,text:clean(req.body?.text,300),createdAt:new Date().toISOString()};if(!c.text)return res.status(400).json({error:'Comment required'});l.comments.push(c);broadcast({type:'live_comment',liveId:l.id,comment:c});save();res.json(c)});
app.post('/api/lives/:id/guest',auth,(req,res)=>{const l=arr('lives').find(x=>x.id===req.params.id&&x.userId===req.user.id&&x.status==='live');if(!l)return res.status(404).json({error:'LIVE not found'});const guestId=String(req.body?.userId||'');if(!user(guestId))return res.status(404).json({error:'Guest not found'});if(!l.guestIds.includes(guestId)&&l.guestIds.length<3)l.guestIds.push(guestId);save();broadcast({type:'live_guest',live:l});res.json(l)});
app.post('/api/lives/:id/end',auth,(req,res)=>{const l=arr('lives').find(x=>x.id===req.params.id&&x.userId===req.user.id);if(!l)return res.status(404).json({error:'LIVE not found'});l.status='ended';l.endedAt=new Date().toISOString();save();broadcast({type:'live_ended',liveId:l.id});res.json(l)});

app.post('/api/broadcasts',auth,(req,res)=>{const b={id:id('bc'),userId:req.user.id,title:clean(req.body?.title||'Broadcast',100),body:clean(req.body?.body,1000),createdAt:new Date().toISOString()};arr('broadcasts').push(b);save();res.json(b)});
app.get('/api/broadcasts/:userId',auth,(req,res)=>res.json(arr('broadcasts').filter(x=>x.userId===req.params.userId).slice(-50).reverse()));

app.post('/api/subscriptions/:creatorId',auth,(req,res)=>{const creatorId=req.params.creatorId;if(!user(creatorId)||creatorId===req.user.id)return res.status(400).json({error:'Invalid creator'});const i=arr('subscriptions').findIndex(x=>x.userId===req.user.id&&x.creatorId===creatorId&&x.status==='active');if(i>=0){arr('subscriptions').splice(i,1);save();return res.json({subscribed:false})}const s={id:id('sub'),userId:req.user.id,creatorId,status:'active',createdAt:new Date().toISOString(),monthlyCoins:0};arr('subscriptions').push(s);notify(creatorId,'subscription',req.user.name+' subscribed to your creator updates');save();res.json({subscribed:true})});
app.get('/api/subscriptions',auth,(req,res)=>res.json(arr('subscriptions').filter(x=>x.userId===req.user.id&&x.status==='active')));
app.get('/api/creator/:id/subscribers',auth,(req,res)=>res.json(arr('subscriptions').filter(x=>x.creatorId===req.params.id&&x.status==='active').map(x=>publicUser(user(x.userId))).filter(Boolean)));

app.post('/api/drafts',auth,(req,res)=>{const d={id:id('dr'),userId:req.user.id,type:clean(req.body?.type||'video',30),title:clean(req.body?.title,120),description:clean(req.body?.description,500),mediaUrl:String(req.body?.mediaUrl||''),settings:req.body?.settings||{},updatedAt:new Date().toISOString()};arr('drafts').push(d);save();res.json(d)});
app.get('/api/drafts',auth,(req,res)=>res.json(arr('drafts').filter(x=>x.userId===req.user.id).reverse()));
app.delete('/api/drafts/:id',auth,(req,res)=>{const a=arr('drafts');const i=a.findIndex(x=>x.id===req.params.id&&x.userId===req.user.id);if(i<0)return res.status(404).json({error:'Draft not found'});a.splice(i,1);save();res.json({ok:true})});

app.post('/api/group-chats',auth,(req,res)=>{const members=[req.user.id,...(Array.isArray(req.body?.members)?req.body.members:[])].filter((x,i,a)=>user(x)&&a.indexOf(x)===i);if(members.length<2)return res.status(400).json({error:'Add at least one other member'});const g={id:id('gc'),ownerId:req.user.id,name:clean(req.body?.name||'Zelqora Group',80),members,createdAt:new Date().toISOString()};arr('groupChats').push(g);save();res.json(g)});
app.get('/api/group-chats',auth,(req,res)=>res.json(arr('groupChats').filter(x=>x.members.includes(req.user.id))));
app.post('/api/group-chats/:id/message',auth,(req,res)=>{const g=arr('groupChats').find(x=>x.id===req.params.id&&x.members.includes(req.user.id));if(!g)return res.status(404).json({error:'Group not found'});const m={id:id('gm'),groupId:g.id,from:req.user.id,text:clean(req.body?.text,1000),mediaUrl:String(req.body?.mediaUrl||''),type:clean(req.body?.type||'text',20),createdAt:new Date().toISOString()};if(!m.text&&!m.mediaUrl)return res.status(400).json({error:'Message is empty'});arr('messages').push(m);save();broadcast({type:'group_message',message:m});res.json(m)});
app.get('/api/group-chats/:id/messages',auth,(req,res)=>{const g=arr('groupChats').find(x=>x.id===req.params.id&&x.members.includes(req.user.id));if(!g)return res.status(404).json({error:'Group not found'});res.json(db.messages.filter(x=>x.groupId===g.id).slice(-100))});
app.post('/api/messages/:id/reaction',auth,(req,res)=>{const messageId=req.params.id,emoji=clean(req.body?.emoji||'❤️',8);const a=arr('messageReactions');const i=a.findIndex(x=>x.messageId===messageId&&x.userId===req.user.id&&x.emoji===emoji);if(i>=0)a.splice(i,1);else a.push({id:id('mr'),messageId,userId:req.user.id,emoji,createdAt:new Date().toISOString()});save();res.json(a.filter(x=>x.messageId===messageId))});
app.post('/api/messages/:id/forward',auth,(req,res)=>{const m=db.messages.find(x=>x.id===req.params.id);const to=String(req.body?.to||'');if(!m||!user(to))return res.status(404).json({error:'Message or recipient not found'});const f={id:id('m'),from:req.user.id,to,text:m.text||'',mediaUrl:m.mediaUrl||'',forwarded:true,createdAt:new Date().toISOString()};db.messages.push(f);save();notify(to,'message',req.user.name+' forwarded you a message');res.json(f)});

app.post('/api/mutes/:userId',auth,(req,res)=>{const target=req.params.userId;if(!user(target))return res.status(404).json({error:'User not found'});const a=arr('mutes'),i=a.findIndex(x=>x.userId===req.user.id&&x.targetId===target);if(i>=0)a.splice(i,1);else a.push({id:id('mu'),userId:req.user.id,targetId:target,createdAt:new Date().toISOString()});save();res.json({muted:i<0})});
app.post('/api/feed/not-interested',auth,(req,res)=>{const videoId=String(req.body?.videoId||'');if(!video(videoId))return res.status(404).json({error:'Video not found'});const a=arr('notInterested');if(!a.some(x=>x.userId===req.user.id&&x.videoId===videoId))a.push({userId:req.user.id,videoId});save();res.json({ok:true})});
app.post('/api/feed/refresh',auth,(req,res)=>{arr('notInterested').filter(x=>x.userId===req.user.id).forEach(x=>{});res.json({ok:true,message:'Your For You feed has been refreshed. New recommendations will be calculated from your recent activity.'})});
app.put('/api/feed/topics',auth,(req,res)=>{const topics=Array.isArray(req.body?.topics)?req.body.topics.map(x=>clean(x,40)).slice(0,30):[];db.topicPrefs=db.topicPrefs.filter(x=>x.userId!==req.user.id);db.topicPrefs.push({userId:req.user.id,topics});save();res.json({topics})});
app.put('/api/feed/keywords',auth,(req,res)=>{const keywords=Array.isArray(req.body?.keywords)?req.body.keywords.map(x=>clean(x,60)).slice(0,50):[];db.keywordFilters=db.keywordFilters.filter(x=>x.userId!==req.user.id);db.keywordFilters.push({userId:req.user.id,keywords});save();res.json({keywords})});

app.get('/api/search',auth,(req,res)=>{const q=clean(req.query.q,100).toLowerCase();const users=db.users.filter(u=>u.name.toLowerCase().includes(q)).slice(0,20).map(publicUser);const videos=db.videos.filter(v=>(v.title||'').toLowerCase().includes(q)||(v.description||'').toLowerCase().includes(q)||(v.creator||'').toLowerCase().includes(q)).slice(-50).reverse();const hashtags=[...new Set(videos.flatMap(v=>String(v.description||'').match(/#[a-z0-9_]+/gi)||[]))].slice(0,20);const sounds=[...new Set(videos.map(v=>v.sound).filter(Boolean))].slice(0,20);res.json({users,videos,hashtags,sounds,trending:db.videos.slice(-10).map(v=>v.title).filter(Boolean)})});

app.get('/api/creator/studio',auth,(req,res)=>{const mine=db.videos.filter(v=>v.userId===req.user.id), gifts=arr('gifts').filter(g=>g.to===req.user.id), follows=db.follows.filter(x=>x.to===req.user.id);const views=mine.reduce((n,v)=>n+(Number(v.views)||0),0),likes=mine.reduce((n,v)=>n+(v.likedBy?.length||0),0);res.json({videos:mine.length,views,likes,comments:mine.reduce((n,v)=>n+(v.comments?.length||0),0),followers:follows.length,giftsReceived:gifts.length,giftCoins:gifts.reduce((n,g)=>n+(g.creatorShare||0),0),recentVideos:mine.slice(-20).reverse()})});
app.get('/api/creator/earnings',auth,(req,res)=>{const gifts=arr('gifts').filter(g=>g.to===req.user.id),payouts=arr('payouts').filter(p=>p.userId===req.user.id);res.json({giftCoins:gifts.reduce((n,g)=>n+(g.creatorShare||0),0),giftCount:gifts.length,payouts:payouts.slice(-30).reverse()})});

app.post('/api/appeals',auth,(req,res)=>{const a={id:id('ap'),userId:req.user.id,targetType:clean(req.body?.targetType,30),targetId:clean(req.body?.targetId,100),reason:clean(req.body?.reason,1000),status:'open',createdAt:new Date().toISOString()};if(!a.targetType||!a.targetId||!a.reason)return res.status(400).json({error:'Appeal details are required'});arr('appeals').push(a);save();res.json(a)});
app.get('/api/appeals',auth,(req,res)=>res.json(arr('appeals').filter(x=>x.userId===req.user.id).reverse()));
app.post('/api/content-reports',auth,(req,res)=>{const r={id:id('cr'),reporterId:req.user.id,targetType:clean(req.body?.targetType,30),targetId:clean(req.body?.targetId,100),reason:clean(req.body?.reason,300),copyright:!!req.body?.copyright,status:'open',createdAt:new Date().toISOString()};arr('videoReports').push(r);save();res.json({ok:true,id:r.id})});
};