const express=require('express'),http=require('http'),cors=require('cors'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),fs=require('fs'),path=require('path'),crypto=require('crypto'),WebSocket=require('ws'),multer=require('multer');
const app=express(),server=http.createServer(app),PORT=process.env.PORT||3000,SECRET=process.env.JWT_SECRET||'change-this-secret';
const VERSION='10.0.0';
if(SECRET==='change-this-secret' && process.env.NODE_ENV==='production') throw new Error('JWT_SECRET must be set in production');
const UPLOAD_DIR=path.join(__dirname,'uploads'); fs.mkdirSync(UPLOAD_DIR,{recursive:true});
const WS_PATH='/ws';
const DB_FILE=path.join(__dirname,'data.json');
function fresh(){return {users:[],messages:[],videos:[],notifications:[],wallets:{},transactions:[],gifts:[],payouts:[],follows:[],stories:[],reports:[],blocks:[],sessions:[],meta:{welcomeRewardRecipients:[]}}}
let db;try{db=JSON.parse(fs.readFileSync(DB_FILE,'utf8'))}catch{db=fresh()}
for(const k of ['users','messages','videos','notifications','transactions','gifts','payouts','follows','stories','reports','blocks','sessions'])if(!Array.isArray(db[k]))db[k]=[];if(!db.wallets)db.wallets={};if(!db.meta)db.meta={welcomeRewardRecipients:[]};if(!Array.isArray(db.meta.welcomeRewardRecipients))db.meta.welcomeRewardRecipients=[];
function save(){fs.writeFileSync(DB_FILE,JSON.stringify(db,null,2))}
function id(prefix){return prefix+crypto.randomBytes(6).toString('hex')}
const online=new Map();
function broadcast(payload){const raw=JSON.stringify(payload);for(const ws of online.values()){if(ws.readyState===1)ws.send(raw)}}
const allowedOrigins=(process.env.CORS_ORIGINS||'').split(',').map(x=>x.trim()).filter(Boolean);
app.use(cors({origin:(origin,cb)=>{if(!origin||allowedOrigins.length===0||allowedOrigins.includes(origin)) return cb(null,true); cb(new Error('Origin not allowed'));}}));
app.disable('x-powered-by');
app.use((req,res,next)=>{res.setHeader('X-Request-ID',crypto.randomUUID());res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('Permissions-Policy','camera=(self),microphone=(self),geolocation=()');next()});
app.use(express.json({limit:'1mb'}));app.use('/uploads',express.static(UPLOAD_DIR,{maxAge:'7d'}));app.use(express.static('public'));
const hits=new Map(); function limit(windowMs,max){return (req,res,next)=>{const key=(req.ip||'ip')+':'+req.path;const now=Date.now(),old=hits.get(key);if(!old||now-old.start>windowMs){hits.set(key,{start:now,count:1});return next()}old.count++;if(old.count>max)return res.status(429).json({error:'Too many requests. Try again later.'});next()}}
app.use('/api/auth/',limit(15*60*1000,30)); app.use('/api/reports',limit(10*60*1000,10));

function auth(req,res,next){try{req.user=jwt.verify((req.headers.authorization||'').replace('Bearer ','').trim(),SECRET);if(!user(req.user.id)) throw new Error('user');next()}catch{res.status(401).json({error:'Authentication required'})}}
function admin(req,res,next){const u=user(req.user.id);if(!u||u.role!=='admin')return res.status(403).json({error:'Admin access required'});next()}
function user(id){return db.users.find(u=>u.id===id)} function ensureWallet(id){if(!db.wallets[id])db.wallets[id]={coins:0,premium:false};return db.wallets[id]}
const COIN_NGN_VALUE=50;const FX_URL=process.env.FX_RATES_URL||'https://open.er-api.com/v6/latest/USD';let fxCache={rates:null,updatedAt:0};async function getFxRates(){const now=Date.now();if(fxCache.rates&&now-fxCache.updatedAt<15*60*1000)return fxCache.rates;const r=await fetch(FX_URL);if(!r.ok)throw new Error('FX rate service unavailable');const d=await r.json();if(!d.rates||!d.rates.NGN)throw new Error('NGN FX rate unavailable');fxCache={rates:{USD:1,...d.rates},updatedAt:now};return fxCache.rates}function walletValue(wallet,rates){const usdPerCoin=COIN_NGN_VALUE/rates.NGN;return {coins:wallet.coins,usd:Number((wallet.coins*usdPerCoin).toFixed(2)),ngn:Number((wallet.coins*COIN_NGN_VALUE).toFixed(2)),coinNgnValue:COIN_NGN_VALUE,usdPerCoin:Number(usdPerCoin.toFixed(6)),rateUpdatedAt:new Date(fxCache.updatedAt).toISOString()}}function notify(userId,type,text){db.notifications.push({id:'n'+Date.now()+Math.random().toString(36).slice(2,6),userId,type,text,read:false,createdAt:new Date().toISOString()})}
function publicUser(u){return {id:u.id,name:u.name,email:u.email,bio:u.bio,avatar:u.avatar,verified:!!u.verified,followers:db.follows.filter(x=>x.to===u.id).length,following:db.follows.filter(x=>x.from===u.id).length}}

const storage=multer.diskStorage({destination:(req,file,cb)=>cb(null,UPLOAD_DIR),filename:(req,file,cb)=>cb(null,Date.now()+'-'+crypto.randomBytes(8).toString('hex')+path.extname(file.originalname).toLowerCase())});
const upload=multer({storage,limits:{fileSize:100*1024*1024},fileFilter:(req,file,cb)=>{const ok=/^(video|image|audio)\/(mp4|webm|quicktime|jpeg|png|webp|gif|mpeg|wav|ogg)$/i.test(file.mimetype);cb(ok?null:new Error('Unsupported media type'),ok)}});
app.post('/api/upload',auth,upload.single('file'),(req,res)=>{if(!req.file)return res.status(400).json({error:'No file uploaded'});res.json({ok:true,url:'/uploads/'+req.file.filename,mime:req.file.mimetype,size:req.file.size})});
app.post('/api/account/change-password',auth,async(req,res)=>{const u=user(req.user.id),{currentPassword,newPassword}=req.body||{};if(!currentPassword||!newPassword||String(newPassword).length<8)return res.status(400).json({error:'Current password and a new password of at least 8 characters are required'});if(!(await bcrypt.compare(currentPassword,u.hash)))return res.status(401).json({error:'Current password is incorrect'});u.hash=await bcrypt.hash(newPassword,12);save();res.json({ok:true})});
app.delete('/api/account',auth,(req,res)=>{const uid=req.user.id;db.users=db.users.filter(u=>u.id!==uid);db.messages=db.messages.filter(m=>m.from!==uid&&m.to!==uid);db.notifications=db.notifications.filter(n=>n.userId!==uid);db.follows=db.follows.filter(f=>f.from!==uid&&f.to!==uid);db.blocks=db.blocks.filter(b=>b.from!==uid&&b.to!==uid);db.stories=db.stories.filter(s=>s.userId!==uid);db.videos=db.videos.filter(v=>v.userId!==uid);delete db.wallets[uid];save();res.json({ok:true})});
app.get('/api/admin/reports',auth,admin,(req,res)=>res.json(db.reports.slice().reverse()));
app.patch('/api/admin/reports/:id',auth,admin,(req,res)=>{const r=db.reports.find(x=>x.id===req.params.id);if(!r)return res.status(404).json({error:'Report not found'});r.status=String(req.body.status||'reviewed').slice(0,30);r.reviewedAt=new Date().toISOString();save();res.json(r)});
app.get('/api/legal/terms',(req,res)=>res.sendFile(path.join(__dirname,'public','terms.html')));app.get('/api/legal/privacy',(req,res)=>res.sendFile(path.join(__dirname,'public','privacy.html')));
app.get('/api/health',(q,s)=>s.json({ok:true,app:'Zelqora',version:VERSION,environment:process.env.NODE_ENV||'development',features:['vertical-feed','stories','following','realtime-chat','notifications','creator-tools','moderation','account-controls','media-upload']}));
app.get('/api/ready',(q,s)=>{const checks={dataWritable:false,uploadsWritable:false};try{fs.accessSync(DB_FILE,fs.constants.W_OK);checks.dataWritable=true}catch{}try{fs.accessSync(UPLOAD_DIR,fs.constants.W_OK);checks.uploadsWritable=true}catch{}const ready=checks.dataWritable&&checks.uploadsWritable;s.status(ready?200:503).json({ready,checks,version:VERSION})});
app.post('/api/auth/register',async(req,res)=>{let{name,email,password}=req.body||{};email=String(email||'').trim().toLowerCase();if(!name||!email||!password)return res.status(400).json({error:'Name, email and password are required'});if(db.users.some(u=>u.email===email))return res.status(409).json({error:'Email already registered'});if(String(password).length<8)return res.status(400).json({error:'Password must be at least 8 characters'});let u={id:'u'+crypto.randomBytes(8).toString('hex'),name:String(name).trim().slice(0,40),email,hash:await bcrypt.hash(password,12),bio:'',avatar:'',verified:false,role:(process.env.ADMIN_EMAIL&&email===process.env.ADMIN_EMAIL.toLowerCase()?'admin':'user'),createdAt:new Date().toISOString()};db.users.push(u);const w=ensureWallet(u.id);let welcomeBonus=0;if(db.meta.welcomeRewardRecipients.length<10){welcomeBonus=10;w.coins+=welcomeBonus;db.meta.welcomeRewardRecipients.push(u.id);db.transactions.push({id:'t'+Date.now(),userId:u.id,type:'welcome_bonus',coins:welcomeBonus,createdAt:new Date().toISOString(),note:'One-time launch reward for one of the first 10 registered users'});notify(u.id,'welcome','🎉 You are one of the first 10 Zelqora users! 10 free coins were added to your wallet.')}save();let token=jwt.sign({id:u.id,name:u.name,email:u.email},SECRET,{expiresIn:'7d'});res.json({token,user:publicUser(u),welcomeBonus})});
app.post('/api/auth/login',async(req,res)=>{let{email,password}=req.body||{},u=db.users.find(x=>x.email===String(email||'').toLowerCase());if(!u||!(await bcrypt.compare(password||'',u.hash)))return res.status(401).json({error:'Invalid email or password'});let token=jwt.sign({id:u.id,name:u.name,email:u.email},SECRET,{expiresIn:'7d'});res.json({token,user:publicUser(u)})});
app.get('/api/me',auth,(req,res)=>res.json(publicUser(user(req.user.id))));
app.patch('/api/me',auth,(req,res)=>{let u=user(req.user.id);if(req.body.name!==undefined)u.name=String(req.body.name).trim().slice(0,40);if(req.body.bio!==undefined)u.bio=String(req.body.bio).slice(0,240);if(req.body.avatar!==undefined)u.avatar=String(req.body.avatar);save();res.json(publicUser(u))});
app.get('/api/users',auth,(req,res)=>{let q=String(req.query.q||'').toLowerCase();res.json(db.users.filter(u=>u.id!==req.user.id&&(!q||u.name.toLowerCase().includes(q)||u.email.includes(q))).slice(0,50).map(publicUser))});
app.get('/api/users/:id',auth,(req,res)=>{let u=user(req.params.id);if(!u)return res.status(404).json({error:'User not found'});res.json({...publicUser(u),following:db.follows.some(x=>x.from===req.user.id&&x.to===u.id)})});
app.post('/api/users/:id/follow',auth,(req,res)=>{let id=req.params.id;if(!user(id)||id===req.user.id)return res.status(400).json({error:'Invalid user'});let i=db.follows.findIndex(x=>x.from===req.user.id&&x.to===id);if(i>=0)db.follows.splice(i,1);else{db.follows.push({from:req.user.id,to:id,createdAt:new Date().toISOString()});notify(id,'follow',`${req.user.name} started following you`)}save();res.json({following:i<0})});
function isBlocked(a,b){return db.blocks.some(x=>(x.from===a&&x.to===b)||(x.from===b&&x.to===a))}
app.post('/api/users/:id/block',auth,(req,res)=>{const id2=req.params.id;if(!user(id2)||id2===req.user.id)return res.status(400).json({error:'Invalid user'});const i=db.blocks.findIndex(x=>x.from===req.user.id&&x.to===id2);if(i>=0)db.blocks.splice(i,1);else db.blocks.push({id:id('b'),from:req.user.id,to:id2,createdAt:new Date().toISOString()});save();res.json({blocked:i<0})});
app.get('/api/users/:id/block-status',auth,(req,res)=>res.json({blocked:isBlocked(req.user.id,req.params.id)}));
app.post('/api/reports',auth,(req,res)=>{const {targetType,targetId,reason}=req.body||{};if(!targetType||!targetId||!reason)return res.status(400).json({error:'Target and reason are required'});db.reports.push({id:id('r'),reporterId:req.user.id,targetType,targetId,reason:String(reason).slice(0,300),status:'open',createdAt:new Date().toISOString()});save();res.json({ok:true,message:'Report submitted'});});
app.get('/api/saved',auth,(req,res)=>res.json(db.videos.filter(v=>(v.savedBy||[]).includes(req.user.id)).map(v=>({...v,likes:(v.likedBy||[]).length,savedByMe:true}))));

app.get('/api/chats/:userId',auth,(req,res)=>{let other=req.params.userId;if(isBlocked(req.user.id,other))return res.status(403).json({error:'Messaging unavailable because one of you blocked the other'});res.json(db.messages.filter(m=>(m.from===req.user.id&&m.to===other)||(m.from===other&&m.to===req.user.id)).slice(-100))});
app.post('/api/chats/:userId',auth,(req,res)=>{let to=req.params.userId,text=String(req.body.text||'').trim();if(!user(to))return res.status(404).json({error:'User not found'});if(isBlocked(req.user.id,to))return res.status(403).json({error:'Messaging unavailable because one of you blocked the other'});if(!text)return res.status(400).json({error:'Message is required'});let m={id:'m'+Date.now()+Math.random().toString(36).slice(2,6),from:req.user.id,to,text,createdAt:new Date().toISOString()};db.messages.push(m);notify(to,'message',`${req.user.name} sent you a message`);save();broadcast({type:'message',message:m});res.json(m)});
app.get('/api/notifications',auth,(req,res)=>res.json(db.notifications.filter(n=>n.userId===req.user.id).slice(-80).reverse()));app.post('/api/notifications/read',auth,(req,res)=>{db.notifications.filter(n=>n.userId===req.user.id).forEach(n=>n.read=true);save();res.json({ok:true})});
function decorateVideo(v){return {...v,likedByMe:v.likedBy?.includes(this?.id)||false,savedByMe:v.savedBy?.includes(this?.id)||false,likes:v.likedBy?.length||0,comments:v.comments||[]}}
app.get('/api/feed',auth,(req,res)=>{let following=new Set(db.follows.filter(x=>x.from===req.user.id).map(x=>x.to));let videos=db.videos.map(v=>({...v,likes:v.likedBy?.length||0,likedByMe:(v.likedBy||[]).includes(req.user.id),savedByMe:(v.savedBy||[]).includes(req.user.id)}));let mode=req.query.mode==='following';if(mode)videos=videos.filter(v=>following.has(v.userId)||v.userId===req.user.id);videos.sort((a,b)=>{let sa=(a.likes*4)+(a.comments.length*6)+(a.views||0)+(following.has(a.userId)?20:0)+(new Date(a.createdAt).getTime()/1e10);let sb=(b.likes*4)+(b.comments.length*6)+(b.views||0)+(following.has(b.userId)?20:0)+(new Date(b.createdAt).getTime()/1e10);return sb-sa});res.json(videos.slice(0,100))});
app.post('/api/videos',auth,(req,res)=>{let{title,description,url,thumbnail}=req.body||{};if(!title||!url)return res.status(400).json({error:'Title and video URL are required'});let v={id:'v'+Date.now()+Math.random().toString(36).slice(2,5),userId:req.user.id,creator:req.user.name,title:String(title).slice(0,120),description:String(description||'').slice(0,500),url:String(url),thumbnail:String(thumbnail||''),likedBy:[],savedBy:[],comments:[],views:0,createdAt:new Date().toISOString()};db.videos.push(v);save();res.json(v)});
app.post('/api/videos/:id/view',auth,(req,res)=>{let v=db.videos.find(x=>x.id===req.params.id);if(!v)return res.status(404).json({error:'Video not found'});v.views=(v.views||0)+1;save();res.json({views:v.views})});
app.post('/api/videos/:id/like',auth,(req,res)=>{let v=db.videos.find(x=>x.id===req.params.id);if(!v)return res.status(404).json({error:'Video not found'});v.likedBy=v.likedBy||[];let i=v.likedBy.indexOf(req.user.id);if(i>=0)v.likedBy.splice(i,1);else{v.likedBy.push(req.user.id);if(v.userId!==req.user.id)notify(v.userId,'like',`${req.user.name} liked your video`)}save();res.json({liked:i<0,likes:v.likedBy.length})});
app.post('/api/videos/:id/save',auth,(req,res)=>{let v=db.videos.find(x=>x.id===req.params.id);if(!v)return res.status(404).json({error:'Video not found'});v.savedBy=v.savedBy||[];let i=v.savedBy.indexOf(req.user.id);if(i>=0)v.savedBy.splice(i,1);else v.savedBy.push(req.user.id);save();res.json({saved:i<0})});
app.post('/api/videos/:id/comments',auth,(req,res)=>{let v=db.videos.find(x=>x.id===req.params.id),text=String(req.body.text||'').trim();if(!v)return res.status(404).json({error:'Video not found'});if(!text)return res.status(400).json({error:'Comment is required'});let c={id:'c'+Date.now(),userId:req.user.id,name:req.user.name,text:text.slice(0,300),createdAt:new Date().toISOString()};v.comments=v.comments||[];v.comments.push(c);save();if(v.userId!==req.user.id)notify(v.userId,'comment',`${req.user.name} commented on your video`);res.json(c)});
app.get('/api/discover',auth,(req,res)=>{let q=String(req.query.q||'').toLowerCase();let users=db.users.filter(u=>u.name.toLowerCase().includes(q)||u.bio.toLowerCase().includes(q)).slice(0,20).map(publicUser);let videos=db.videos.filter(v=>!q||v.title.toLowerCase().includes(q)||v.description.toLowerCase().includes(q)||v.creator.toLowerCase().includes(q)).slice(-30).reverse();res.json({users,videos})});
app.get('/api/stories',auth,(req,res)=>{let cutoff=Date.now()-86400000;res.json(db.stories.filter(s=>new Date(s.createdAt).getTime()>cutoff).reverse())});
app.post('/api/stories',auth,(req,res)=>{let{url,text}=req.body||{};if(!url&&!text)return res.status(400).json({error:'Story needs media URL or text'});let s={id:'s'+Date.now(),userId:req.user.id,name:req.user.name,avatar:user(req.user.id).avatar,url:String(url||''),text:String(text||'').slice(0,180),createdAt:new Date().toISOString()};db.stories.push(s);save();res.json(s)});
app.get('/api/settings',auth,(req,res)=>res.json({privacy:{publicProfile:true,allowMessages:!db.blocks.some(x=>x.to===req.user.id&&x.from===req.user.id)},safety:{reporting:true,blocking:true}}));
app.delete('/api/me',auth,(req,res)=>{const uid=req.user.id;db.users=db.users.filter(u=>u.id!==uid);db.messages=db.messages.filter(m=>m.from!==uid&&m.to!==uid);db.videos=db.videos.filter(v=>v.userId!==uid);db.follows=db.follows.filter(f=>f.from!==uid&&f.to!==uid);db.notifications=db.notifications.filter(n=>n.userId!==uid);delete db.wallets[uid];save();res.json({ok:true})});

app.post('/api/devices',auth,(req,res)=>{const {platform,token}=req.body||{};if(!['android','ios','web'].includes(platform)||!token||String(token).length>512)return res.status(400).json({error:'Valid platform and device token are required'});db.sessions=db.sessions||[];db.sessions=db.sessions.filter(x=>!(x.userId===req.user.id&&x.token===token));db.sessions.push({id:id('d'),userId:req.user.id,platform,token:String(token),createdAt:new Date().toISOString()});save();res.json({ok:true})});
app.delete('/api/devices/:token',auth,(req,res)=>{db.sessions=(db.sessions||[]).filter(x=>!(x.userId===req.user.id&&x.token===req.params.token));save();res.json({ok:true})});
app.get('/api/moderation/summary',auth,admin,(req,res)=>res.json({openReports:db.reports.filter(r=>r.status==='open').length,users:db.users.length,videos:db.videos.length,messages:db.messages.length,blockedRelations:db.blocks.length}));
app.get('/api/wallet',auth,async(req,res)=>{try{const w=ensureWallet(req.user.id),rates=await getFxRates();res.json({...walletValue(w,rates),premium:!!w.premium,displayCurrency:'USD',supportedCurrencies:Object.keys(rates).sort()})}catch(e){res.status(503).json({error:'Currency rates are temporarily unavailable. Please try again.'})}});app.get('/api/wallet/transactions',auth,(req,res)=>res.json(db.transactions.filter(x=>x.userId===req.user.id).slice(-50).reverse()));app.get('/api/wallet/quote',auth,async(req,res)=>{try{const currency=String(req.query.currency||'USD').toUpperCase(),rates=await getFxRates();if(!rates[currency])return res.status(400).json({error:'Unsupported currency'});const w=ensureWallet(req.user.id),v=walletValue(w,rates);res.json({currency,coins:w.coins,usdValue:v.usd,localValue:Number((v.usd*rates[currency]).toFixed(2)),coinLocalValue:Number((COIN_NGN_VALUE/rates.NGN*rates[currency]).toFixed(4)),coinNgnValue:COIN_NGN_VALUE,updatedAt:v.rateUpdatedAt})}catch(e){res.status(503).json({error:'Currency rates are temporarily unavailable. Please try again.'})}});
app.post('/api/wallet/test-topup',auth,(req,res)=>{let amount=Math.max(1,Math.min(100000,Number(req.body.coins)||0));let w=ensureWallet(req.user.id);w.coins+=amount;let t={id:'t'+Date.now(),userId:req.user.id,type:'test_topup',coins:amount,createdAt:new Date().toISOString()};db.transactions.push(t);save();res.json({wallet:w,transaction:t,note:'TEST MODE ONLY — no real money was charged.'})});
app.post('/api/premium/test',auth,(req,res)=>{let w=ensureWallet(req.user.id);w.premium=true;db.transactions.push({id:'t'+Date.now(),userId:req.user.id,type:'premium_test',coins:0,createdAt:new Date().toISOString()});save();res.json({wallet:w,note:'TEST MODE ONLY'});});
app.post('/api/gifts',auth,(req,res)=>{let{creatorId,coins}=req.body||{},n=Number(coins)||0;if(!creatorId||n<1)return res.status(400).json({error:'Creator and coin amount are required'});if(!user(creatorId))return res.status(404).json({error:'Creator not found'});let sender=ensureWallet(req.user.id);if(sender.coins<n)return res.status(400).json({error:'Not enough coins'});sender.coins-=n;let share=Math.floor(n*.7);ensureWallet(creatorId).coins+=share;let now=new Date().toISOString(),g={id:'g'+Date.now(),from:req.user.id,to:creatorId,coins:n,creatorShare:share,createdAt:now};db.gifts.push(g);db.transactions.push({id:'t'+Date.now()+'a',userId:req.user.id,type:'gift_sent',coins:-n,createdAt:now},{id:'t'+Date.now()+'b',userId:creatorId,type:'gift_received',coins:share,createdAt:now});notify(creatorId,'gift',`${req.user.name} sent you a creator gift`);save();res.json(g)});
app.post('/api/payout/request',auth,(req,res)=>{let w=ensureWallet(req.user.id),coins=Number(req.body.coins)||0;if(coins<100)return res.status(400).json({error:'Minimum payout is 100 creator coins in this prototype'});if(w.coins<coins)return res.status(400).json({error:'Insufficient creator balance'});w.coins-=coins;let p={id:'p'+Date.now(),userId:req.user.id,coins,status:'pending',createdAt:new Date().toISOString()};db.payouts.push(p);db.transactions.push({id:'t'+Date.now(),userId:req.user.id,type:'payout_pending',coins:-coins,createdAt:p.createdAt});save();res.json({p,note:'Payout is simulated. Connect a real payout provider before withdrawals.'})});
app.get('*',(q,s)=>q.path.startsWith('/api/')?s.status(404).json({error:'Not found'}):s.sendFile(path.join(__dirname,'public','index.html')));
const wss=new WebSocket.Server({server,path:WS_PATH});
wss.on('connection',(ws,req)=>{try{const token=(new URL(req.url,'http://localhost')).searchParams.get('token');const decoded=jwt.verify(token||'',SECRET);online.set(decoded.id,ws);ws.send(JSON.stringify({type:'connected',userId:decoded.id}));ws.on('close',()=>online.delete(decoded.id));ws.on('error',()=>online.delete(decoded.id));}catch{ws.close(1008,'Authentication required')}});
const shutdown=()=>server.close(()=>process.exit(0));process.on('SIGTERM',shutdown);process.on('SIGINT',shutdown);
server.listen(PORT,()=>console.log(`Zelqora ${VERSION} on ${PORT}`));
