module.exports=function(app,ctx){
const {db,save,id,user,auth,notify,publicUser}=ctx;
const arr=k=>{if(!Array.isArray(db[k]))db[k]=[];return db[k]};
function purchaseLock(key){if(!db.__purchaseLocks)db.__purchaseLocks={};if(db.__purchaseLocks[key])return false;db.__purchaseLocks[key]=Date.now();return true}
function clearPurchaseLock(key){if(db.__purchaseLocks)delete db.__purchaseLocks[key]}
for(const k of ['privacy','notificationPrefs','postSettings','sounds','deletedVideos','series','seriesPurchases','pinned','verificationRequests','promotions','fanClubs','fanClubMembers','securityPins','accessibility','aiDrafts'])arr(k);
const clean=(s,n=500)=>String(s??'').trim().slice(0,n),now=()=>new Date().toISOString();
const wallet=uid=>{if(!db.wallets[uid])db.wallets[uid]={coins:0,creatorEarningsCoins:0,premium:false,payoutAccount:null};return db.wallets[uid]};
const isAdmin=req=>{const u=user(req.user.id);return !!u&&u.role==='admin'};

app.get('/api/privacy',auth,(req,res)=>res.json(arr('privacy').find(x=>x.userId===req.user.id)||{userId:req.user.id,privateAccount:false,allowMessages:true,allowComments:true,allowMentions:true,showActivityStatus:true,allowDownloads:true}));
app.put('/api/privacy',auth,(req,res)=>{let p=arr('privacy').find(x=>x.userId===req.user.id);if(!p){p={userId:req.user.id};arr('privacy').push(p)}for(const k of ['privateAccount','allowMessages','allowComments','allowMentions','showActivityStatus','allowDownloads'])if(req.body[k]!==undefined)p[k]=!!req.body[k];save();res.json(p)});

app.get('/api/notifications/preferences',auth,(req,res)=>res.json(arr('notificationPrefs').find(x=>x.userId===req.user.id)||{userId:req.user.id,likes:true,comments:true,followers:true,messages:true,gifts:true,live:true,promotions:false}));
app.put('/api/notifications/preferences',auth,(req,res)=>{let p=arr('notificationPrefs').find(x=>x.userId===req.user.id);if(!p){p={userId:req.user.id};arr('notificationPrefs').push(p)}for(const k of ['likes','comments','followers','messages','gifts','live','promotions'])if(req.body[k]!==undefined)p[k]=!!req.body[k];save();res.json(p)});

app.get('/api/videos/:id/settings',auth,(req,res)=>{const v=db.videos.find(x=>x.id===req.params.id);if(!v)return res.status(404).json({error:'Video not found'});res.json(arr('postSettings').find(x=>x.videoId===v.id&&x.userId===req.user.id)||{videoId:v.id,userId:req.user.id,privacy:'public',allowComments:true,allowDuet:true,allowStitch:true,allowDownloads:true,allowRepost:true})});
app.put('/api/videos/:id/settings',auth,(req,res)=>{const v=db.videos.find(x=>x.id===req.params.id);if(!v||v.userId!==req.user.id)return res.status(403).json({error:'You can only edit your own video settings'});let s=arr('postSettings').find(x=>x.videoId===v.id&&x.userId===req.user.id);if(!s){s={videoId:v.id,userId:req.user.id};arr('postSettings').push(s)}for(const k of ['privacy','allowComments','allowDuet','allowStitch','allowDownloads','allowRepost'])if(req.body[k]!==undefined)s[k]=k==='privacy'?clean(req.body[k],20):!!req.body[k];save();res.json(s)});

app.get('/api/sounds',auth,(req,res)=>{const q=clean(req.query.q,80).toLowerCase(),base=arr('sounds').filter(s=>!q||s.name.toLowerCase().includes(q)).slice(-100).reverse(),used=db.videos.map(v=>v.sound).filter(Boolean),built=[...new Set(used)].map(name=>({id:'sound-'+encodeURIComponent(name),name,creator:'Zelqora community'}));res.json([...base,...built].slice(0,100))});
app.post('/api/sounds',auth,(req,res)=>{const name=clean(req.body?.name,80),url=clean(req.body?.url,500);if(!name)return res.status(400).json({error:'Sound name required'});const s={id:id('snd'),name,url,creatorId:req.user.id,creator:req.user.name,createdAt:now()};arr('sounds').push(s);save();res.json(s)});

app.post('/api/videos/:id/pin',auth,(req,res)=>{const v=db.videos.find(x=>x.id===req.params.id);if(!v||v.userId!==req.user.id)return res.status(403).json({error:'Not your video'});const a=arr('pinned'),i=a.findIndex(x=>x.userId===req.user.id&&x.videoId===v.id);if(i>=0)a.splice(i,1);else{if(a.filter(x=>x.userId===req.user.id).length>=3)return res.status(400).json({error:'Maximum 3 pinned videos'});a.push({id:id('pin'),userId:req.user.id,videoId:v.id,createdAt:now()})}save();res.json({pinned:i<0})});
app.get('/api/pinned/:userId',auth,(req,res)=>res.json(arr('pinned').filter(x=>x.userId===req.params.userId).map(x=>db.videos.find(v=>v.id===x.videoId)).filter(Boolean)));

app.delete('/api/videos/:id',auth,(req,res)=>{const i=db.videos.findIndex(v=>v.id===req.params.id&&v.userId===req.user.id);if(i<0)return res.status(404).json({error:'Video not found'});const v=db.videos.splice(i,1)[0];arr('deletedVideos').push({id:id('trash'),deletedBy:req.user.id,deletedAt:now(),restoreUntil:Date.now()+30*24*60*60*1000,video:v});save();res.json({ok:true,message:'Video moved to Recently Deleted for 30 days'})});
app.get('/api/recently-deleted',auth,(req,res)=>res.json(arr('deletedVideos').filter(x=>x.deletedBy===req.user.id&&Date.now()<x.restoreUntil)));
app.post('/api/recently-deleted/:id/restore',auth,(req,res)=>{const a=arr('deletedVideos'),i=a.findIndex(x=>x.id===req.params.id&&x.deletedBy===req.user.id&&Date.now()<x.restoreUntil);if(i<0)return res.status(404).json({error:'Deleted video not found or recovery period expired'});const x=a.splice(i,1)[0];db.videos.push(x.video);save();res.json(x.video)});

app.post('/api/series',auth,(req,res)=>{const title=clean(req.body?.title,120),description=clean(req.body?.description,1000),price=Math.max(0,Math.floor(Number(req.body?.priceCoins)||0));if(!title)return res.status(400).json({error:'Series title required'});if(price>1000000)return res.status(400).json({error:'Invalid Series price'});const s={id:id('ser'),creatorId:req.user.id,title,description,priceCoins:price,videoIds:[],published:false,createdAt:now()};arr('series').push(s);save();res.json(s)});
app.get('/api/series/:id',auth,(req,res)=>{const s=arr('series').find(x=>x.id===req.params.id);if(!s)return res.status(404).json({error:'Series not found'});const owned=s.creatorId===req.user.id||arr('seriesPurchases').some(x=>x.seriesId===s.id&&x.userId===req.user.id);if(!owned)return res.json({...s,videoIds:[],locked:true,canPurchase:true});res.json({...s,locked:false,canPurchase:false})});
app.post('/api/series/:id/videos',auth,(req,res)=>{const s=arr('series').find(x=>x.id===req.params.id&&x.creatorId===req.user.id),v=db.videos.find(x=>x.id===req.body?.videoId);if(!s||!v)return res.status(404).json({error:'Series or video not found'});if(v.userId!==req.user.id)return res.status(403).json({error:'Not your video'});if(!s.videoIds.includes(v.id))s.videoIds.push(v.id);save();res.json(s)});
app.post('/api/series/:id/purchase',auth,(req,res)=>{const lockKey='series:'+req.params.id+':'+req.user.id;if(!purchaseLock(lockKey))return res.status(409).json({error:'Purchase already processing'});try{const s=arr('series').find(x=>x.id===req.params.id);if(!s)return res.status(404).json({error:'Series not found'});if(s.creatorId===req.user.id)return res.status(400).json({error:'You cannot purchase your own Series'});if(arr('seriesPurchases').some(x=>x.seriesId===s.id&&x.userId===req.user.id))return res.json({purchased:true,alreadyPurchased:true});const price=Math.max(0,Math.floor(Number(s.priceCoins)||0));if(price<=0)return res.status(400).json({error:'Series price must be greater than zero'});const w=wallet(req.user.id);const spendable=Math.max(0,(Number(w.coins)||0)-(Number(w.creatorEarningsCoins)||0));if(spendable<price)return res.status(400).json({error:'Not enough spendable coins'});w.coins-=price;const creator=wallet(s.creatorId),share=Math.floor(price*0.70);creator.coins=(creator.coins||0)+share;creator.creatorEarningsCoins=(creator.creatorEarningsCoins||0)+share;const p={id:id('sp'),seriesId:s.id,userId:req.user.id,coins:price,creatorShare:share,createdAt:now()};arr('seriesPurchases').push(p);db.transactions.push({id:id('t'),userId:req.user.id,type:'series_purchase',coins:-price,creatorId:s.creatorId,reference:s.id,createdAt:now()});notify(s.creatorId,'series',req.user.name+' purchased your Series');save();res.json({purchased:true,coins:price,creatorShare:share})}finally{clearPurchaseLock(lockKey)}});

app.post('/api/verification/request',auth,(req,res)=>{if(arr('verificationRequests').some(x=>x.userId===req.user.id&&x.status==='open'))return res.status(409).json({error:'Verification request already pending'});const r={id:id('vr'),userId:req.user.id,reason:clean(req.body?.reason,1000),status:'open',createdAt:now()};arr('verificationRequests').push(r);save();res.json(r)});
app.get('/api/verification/status',auth,(req,res)=>res.json(arr('verificationRequests').filter(x=>x.userId===req.user.id).slice(-1)[0]||{status:user(req.user.id)?.verified?'verified':'none'}));

app.post('/api/promotions',auth,(req,res)=>{const videoId=String(req.body?.videoId||''),coins=Math.floor(Number(req.body?.coins)||0),v=db.videos.find(x=>x.id===videoId);if(!v||v.userId!==req.user.id)return res.status(404).json({error:'Your video was not found'});if(coins<100)return res.status(400).json({error:'Promotion starts at 100 coins'});const w=wallet(req.user.id);const spendable=Math.max(0,(Number(w.coins)||0)-(Number(w.creatorEarningsCoins)||0));if(spendable<coins)return res.status(400).json({error:'Not enough spendable coins'});w.coins-=coins;const p={id:id('promo'),userId:req.user.id,videoId,coins,status:'active',createdAt:now()};arr('promotions').push(p);save();res.json(p)});
app.get('/api/promotions',auth,(req,res)=>res.json(arr('promotions').filter(x=>x.userId===req.user.id).reverse()));

app.post('/api/fan-club/:creatorId/join',auth,(req,res)=>{const creatorId=req.params.creatorId;if(!user(creatorId)||creatorId===req.user.id)return res.status(400).json({error:'Invalid creator'});let fc=arr('fanClubs').find(x=>x.creatorId===creatorId);if(!fc){fc={id:id('fc'),creatorId,name:'Zelqora Fan Club',createdAt:now()};arr('fanClubs').push(fc)}const a=arr('fanClubMembers'),i=a.findIndex(x=>x.fanClubId===fc.id&&x.userId===req.user.id);if(i>=0)a.splice(i,1);else a.push({id:id('fcm'),fanClubId:fc.id,userId:req.user.id,joinedAt:now(),badge:'Supporter'});save();res.json({joined:i<0,badge:i<0?'Supporter':null})});
app.get('/api/fan-club/:creatorId',auth,(req,res)=>{const fc=arr('fanClubs').find(x=>x.creatorId===req.params.creatorId);if(!fc)return res.json({members:0,joined:false});const members=arr('fanClubMembers').filter(x=>x.fanClubId===fc.id);res.json({id:fc.id,name:fc.name,members:members.length,joined:members.some(x=>x.userId===req.user.id)})});

app.get('/api/creator/advanced-analytics',auth,(req,res)=>{const mine=db.videos.filter(v=>v.userId===req.user.id),views=mine.reduce((n,v)=>n+(Number(v.views)||0),0),likes=mine.reduce((n,v)=>n+(v.likedBy?.length||0),0),comments=mine.reduce((n,v)=>n+(v.comments?.length||0),0),watchTimeSeconds=mine.reduce((n,v)=>n+(Number(v.watchTimeSeconds)||0),0);res.json({videos:mine.length,views,likes,comments,watchTimeSeconds,followers:db.follows.filter(x=>x.to===req.user.id).length,profileVisits:Number(user(req.user.id)?.profileVisits||0),recent:mine.slice(-20).reverse()})});

app.post('/api/security/pin',auth,async(req,res)=>{const bcrypt=require('bcryptjs'),pin=String(req.body?.pin||'');if(!/^\d{4,6}$/.test(pin))return res.status(400).json({error:'PIN must be 4 to 6 digits'});let p=arr('securityPins').find(x=>x.userId===req.user.id);const hash=await bcrypt.hash(pin,10);if(p)p.hash=hash;else arr('securityPins').push({userId:req.user.id,hash,createdAt:now()});save();res.json({ok:true})});
app.post('/api/security/pin/verify',auth,async(req,res)=>{const key='pin:'+req.user.id,nowMs=Date.now();db.__pinAttempts??={};const a=db.__pinAttempts[key]||{start:nowMs,count:0};if(nowMs-a.start>15*60*1000){a.start=nowMs;a.count=0}if(a.count>=5)return res.status(429).json({ok:false,error:'Too many PIN attempts. Try again later.'});a.count++;db.__pinAttempts[key]=a;const bcrypt=require('bcryptjs'),p=arr('securityPins').find(x=>x.userId===req.user.id);if(!p||!(await bcrypt.compare(String(req.body?.pin||''),p.hash)))return res.status(401).json({ok:false});res.json({ok:true})});

app.get('/api/accessibility',auth,(req,res)=>res.json(arr('accessibility').find(x=>x.userId===req.user.id)||{userId:req.user.id,fontScale:1,reducedMotion:false,highContrast:false,captions:true}));
app.put('/api/accessibility',auth,(req,res)=>{let a=arr('accessibility').find(x=>x.userId===req.user.id);if(!a){a={userId:req.user.id};arr('accessibility').push(a)}if(req.body.fontScale!==undefined)a.fontScale=Math.min(1.4,Math.max(.9,Number(req.body.fontScale)||1));for(const k of ['reducedMotion','highContrast','captions'])if(req.body[k]!==undefined)a[k]=!!req.body[k];save();res.json(a)});

app.post('/api/ai/caption',auth,(req,res)=>{const topic=clean(req.body?.topic,120)||'your new Zelqora video';const captions=['✨ '+topic+' — watch till the end!','💫 Sharing a moment about '+topic+'. What do you think?','🔥 '+topic+' — this one is for the Zelqora community!'];const hashtags=['#Zelqora','#ForYou',...topic.toLowerCase().split(/\s+/).filter(x=>x.length>3).slice(0,4).map(x=>'#'+x.replace(/[^a-z0-9]/g,''))];const d={id:id('ai'),userId:req.user.id,topic,captions,hashtags,createdAt:now()};arr('aiDrafts').push(d);save();res.json(d)});

app.get('/api/admin/dashboard',auth,(req,res)=>{if(!isAdmin(req))return res.status(403).json({error:'Admin access required'});res.json({users:db.users.length,videos:db.videos.length,reports:db.reports.length,contentReports:arr('videoReports').length,payments:db.payments.length,payouts:db.payouts.length,live:arr('lives').filter(x=>x.status==='live').length,openAppeals:arr('appeals').filter(x=>x.status==='open').length,verificationRequests:arr('verificationRequests').filter(x=>x.status==='open').length})});
app.get('/api/admin/moderation',auth,(req,res)=>{if(!isAdmin(req))return res.status(403).json({error:'Admin access required'});res.json({reports:db.reports.slice(-100).reverse(),contentReports:arr('videoReports').slice(-100).reverse(),appeals:arr('appeals').slice(-100).reverse(),verification:arr('verificationRequests').slice(-100).reverse()})});
app.patch('/api/admin/moderation/:type/:id',auth,(req,res)=>{if(!isAdmin(req))return res.status(403).json({error:'Admin access required'});const map={report:'reports',content:'videoReports',appeal:'appeals',verification:'verificationRequests'},a=arr(map[req.params.type]||'');const x=a.find(y=>y.id===req.params.id);if(!x)return res.status(404).json({error:'Item not found'});x.status=clean(req.body?.status||'reviewed',30);x.reviewedAt=now();x.reviewedBy=req.user.id;save();res.json(x)});

app.get('/api/receipts',auth,(req,res)=>{const out=[];for(const p of db.payments.filter(x=>x.userId===req.user.id))out.push({id:p.id,type:'coin_purchase',coins:p.coins,amount:p.amountNgn,currency:p.currency,status:p.status,createdAt:p.createdAt});for(const p of arr('productPurchases').filter(x=>x.userId===req.user.id))out.push({id:p.id,type:'creator_store_purchase',coins:p.coins,currency:'COINS',status:'paid',createdAt:p.createdAt});for(const p of db.gifts.filter(x=>x.from===req.user.id))out.push({id:p.id,type:'gift_sent',coins:-p.coins,currency:'COINS',status:'sent',createdAt:p.createdAt});for(const p of db.gifts.filter(x=>x.to===req.user.id))out.push({id:p.id,type:'gift_received',coins:p.creatorShare,currency:'COINS',status:'received',createdAt:p.createdAt});for(const p of db.payouts.filter(x=>x.userId===req.user.id))out.push({id:p.id,type:'creator_withdrawal',coins:p.coins,amount:p.amountNgn,currency:'NGN',status:p.status,createdAt:p.createdAt});for(const p of arr('seriesPurchases').filter(x=>x.userId===req.user.id))out.push({id:p.id,type:'series_purchase',coins:p.coins,currency:'COINS',status:'paid',createdAt:p.createdAt});res.json(out.sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).slice(0,200))});
};